### ISSUE TITLE
About "fan-out" demo 

### ISSUE THREAD

**Issue by Shawn-Fan** [mchmarny/dapr-demos#11]
Should  a config folder be under the "dapr-demos/fan-out/grpc-echo-service/" ?  Thanks

**Comment by mchmarny** [comment]
The echo service demo has no components so the empty folder was not added in git. You can either create an empty `config` folder or remove the `--components-path` flag so the command looks like this: 

```shell
dapr run \
    --app-id grpc-service-demo \
    --app-port 50001 \
    --app-protocol grpc \
    --dapr-http-port 3500 \
    go run main.go
```
